#!/usr/bin/env node
'use strict';
// Writes the served stylesheets from their modules (files.js STYLES): showcase.css = showcase.CSS + the ring icons'
// CSS. `--check` exits 1 when a file differs from what its module would write (test/showcase.test.js runs it).
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');
const OUT = {
    'showcase.css': () => `/* Generated by scripts/build-styles.js from showcase.js and ov-icons.js. Do not edit. */\n${require('../showcase').CSS.trim()}\n${require('../ov-icons').CSS.trim()}\n`,
};
const check = process.argv.includes('--check');
let stale = 0;
for (const [file, make] of Object.entries(OUT)) {
    const want = make();
    const p = path.join(ROOT, file);
    const have = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
    if (have === want) continue;
    if (check) { console.error(`${file} is stale: run node scripts/build-styles.js`); stale++; } else fs.writeFileSync(p, want);
}
process.exit(stale ? 1 : 0);
